version: '3.8'

services:
  # Aplicación Laravel para PRODUCCIÓN
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: laravel_app_prod
    restart: always
    working_dir: /var/www
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    networks:
      - laravel_network
    # depends_on:
    #   - db

  # Servidor web Nginx
  webserver:
    image: nginx:alpine
    container_name: laravel_webserver_prod
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network
    depends_on:
      - app

  # Base de datos MySQL con usuario personalizado
  # db:
  #   image: mysql:8.0
  #   container_name: laravel_db_prod
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "12345678"
  #     MYSQL_DATABASE: "laravel"
  #     MYSQL_USER: "root"
  #     MYSQL_PASSWORD: "12345678"
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql_prod_data:/var/lib/mysql
  #   networks:
  #     - laravel_network

networks:
  laravel_network:
    driver: bridge

# volumes:
#   mysql_prod_data:
#     driver: local