version: '3.8'

services:
  # Aplicación Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./storage/app:/var/www/storage/app
      - ./storage/logs:/var/www/storage/logs
    networks:
      - laravel_network
    # depends_on:
    #   - db

  # Servidor web Nginx
  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network
    depends_on:
      - app

  # # Base de datos MySQL
  # db:
  #   image: mysql:8.0
  #   container_name: laravel_db
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_DATABASE: laravel
  #     MYSQL_ROOT_PASSWORD: "12345678"
  #     MYSQL_USER: "root"
  #     MYSQL_PASSWORD: "12345678"
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   networks:
  #     - laravel_network

networks:
  laravel_network:
    driver: bridge

# volumes:
#   mysql_data:
#     driver: local