[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.prod"

[deploy]
startCommand = "/usr/local/bin/entrypoint.sh" 
healthcheckPath = "/health"  
healthcheckTimeout = 10
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
PORT = "8080"